image: generic-build-image-type-2:v1.0.4

stages:
  - build

build:
  stage: build
  script:
    - cd server && ant dist -f mirth-build-custom.xml
  artifacts:
    paths:
      - server/dist/extensions/*
    expire_in: 1 day
